[project]
name = "mtg-commander-leaderboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.5",
    "sqlalchemy>=2.0.40",
    "streamlit>=1.44.1",
]
